### ISSUE TITLE
InvalidPathException invoking content assist

### ISSUE THREAD

**Issue by bruno-medeiros** [GoClipse/goclipse#112]
```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 40: ,dir.Path+dir.Name,path,err)return}b,err:=json.Marshal(map[string]interface{}{
at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
at sun.nio.fs.WindowsPath.parse(Unknown Source)
at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
at sun.nio.fs.AbstractPath.resolve(Unknown Source)
at com.googlecode.goclipse.go.CodeContext.getExternalCodeContext(CodeContext.java:283)
at com.googlecode.goclipse.go.CodeContext.parseText(CodeContext.java:248)
at com.googlecode.goclipse.go.CodeContext.getCodeContext(CodeContext.java:117)
at com.googlecode.goclipse.go.CodeContext.getCodeContext(CodeContext.java:78)
at com.googlecode.goclipse.ui.editor.GocodeCompletionProposalComputer.computeCompletionProposals(GocodeCompletionProposalComputer.java:80)
at com.googlecode.goclipse.ui.editor.GocodeContentAssistProcessor.doComputeCompletionProposals(GocodeContentAssistProcessor.java:35)
at com.googlecode.goclipse.ui.editor.LangContentAssistProcessor.computeCompletionProposals(LangContentAssistProcessor.java:48)
at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1861)
at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:573)
at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:570)
at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:505)
at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:499)
at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1687)
at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:932)
at org.eclipse.ui.texteditor.ContentAssistAction$1.run(ContentAssistAction.java:82)
at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
at org.eclipse.ui.texteditor.ContentAssistAction.run(ContentAssistAction.java:80)
at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)
at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:122)
```

https://groups.google.com/forum/#!topic/goclipse/xtW8tqh-1PU

--
Seems this is caused by a bug in the CodeContext parser.

**Comment by nero-mtrozzo** [comment]
Thx for the fix!
