### ISSUE TITLE
Outline is empty and is not showing anything (in Mars)

### ISSUE THREAD

**Issue by honzajde** [GoClipse/goclipse#151]
win32, Vista ;)
Installed as described in instructions...

**Comment by honzajde** [comment]
btw. this worked well in Luna, 
don't know how to install old plugin to Luna (it was 0.10) - someone has link to the old binary?

**Comment by honzajde** [comment]
the plugin also states (in Eclipse description) that it's development version and can be broken - I guess that is some licencing mess:)

**Comment by bruno-medeiros** [comment]
Did you configure oracle in Goclipse? As of Goclipse 0.11.0 oracle is required to present the outline.

**Comment by honzajde** [comment]
oracle is configured since I have code completion

**Comment by bruno-medeiros** [comment]
What does the Oracle/gocode log say after you open a Go file?

**Comment by joegrasse** [comment]
@bruno-medeiros isn't code completion provided by gocode not oracle? If so, @honzajde previous statement wouldn't prove that oracle is configured.

**Comment by bruno-medeiros** [comment]
> @bruno-medeiros isn't code completion provided by gocode not oracle? If so, @honzajde previous statement wouldn't prove that oracle is configured.

True, although oracle is used for Open Definition. In any case, the output in the `Oracle/gocode log` console should make clear what the problem is.

**Comment by honzajde** [comment]
I see some errors in Oracle/gocode log

<pre>
C:\Users\Jan\AppData\Local\Temp\_goclipse3341207055694233476\src\describe_temp\describe.go:9:2: could not import github.com/gorilla/websocket (cannot find package "github.com/gorilla/websocket" in any of:
	C:\Go\src\github.com\gorilla\websocket (from $GOROOT)
	C:\Users\Jan\AppData\Local\Temp\_goclipse3341207055694233476\src\github.com\gorilla\websocket (from $GOPATH))
</pre>

My Environemnt variables are the same as the ones set in eclipse IDE

<pre>
GOBIN C:\goprojects\bin
GOPATH C:\goprojects
GOROOT C:\Go
</pre>

The Oraclse/golang log console has following errors:

<pre>
>> Running: C:\goprojects\bin\oracle.exe -pos=C:\Users\Jan\AppData\Local\Temp\_goclipse7284660579731027051\src\describe_temp\describe.go:#8,#8 -format=json describe describe_temp
C:\Users\Jan\AppData\Local\Temp\_goclipse7284660579731027051\src\describe_temp\describe.go:52:43: undeclared name: parse_app_id
</pre>

I noticed, that outline works in another file which is simple enough to have no imports.

I don't understand what is wrong, since I just copied settings from the older version of IDE to the newer one.

It looks like the tool never searches imports on the true GOPATH.

Or maybe I am just silly and missed something obvious;)

**Comment by bruno-medeiros** [comment]
That `undeclared name: parse_app_id` error message is strange. Can you make sure you update to the latest oracle version? The oracle describe operation should work even if the GOPATH is incomplete, or if symbols cannot be resolved.

If it still fails, please post the source of `describe.go`

**Comment by RomanSaveljev** [comment]
Hello, I am also unable to see the outline for a certain file, but I find an exception in the error log:

```
!ENTRY com.googlecode.goclipse.core 2 0 2015-09-19 18:58:58.440
!MESSAGE Error parsing oracle describe result, for source structure update. 
!STACK 0
melnorme.utilbox.core.CommonException: Invalid line, out of bounds.
	at melnorme.lang.tooling.ops.util.SourceLinesInfo.getValidatedOffset(SourceLinesInfo.java:74)
	at com.googlecode.goclipse.tooling.oracle.OraclePackageDescribeParser.parseSourceRange(OraclePackageDescribeParser.java:201)
	at com.googlecode.goclipse.tooling.oracle.OraclePackageDescribeParser.parseStructureElement(OraclePackageDescribeParser.java:128)
	at com.googlecode.goclipse.tooling.oracle.OraclePackageDescribeParser.parseElements(OraclePackageDescribeParser.java:100)
	at com.googlecode.goclipse.tooling.oracle.OraclePackageDescribeParser.parseStructureElement(OraclePackageDescribeParser.java:176)
	at com.googlecode.goclipse.tooling.oracle.OraclePackageDescribeParser.parseElements(OraclePackageDescribeParser.java:100)
	at com.googlecode.goclipse.tooling.oracle.OraclePackageDescribeParser.doParseJsonResult(OraclePackageDescribeParser.java:81)
	at com.googlecode.goclipse.tooling.oracle.OraclePackageDescribeParser.parse(OraclePackageDescribeParser.java:64)
	at com.googlecode.goclipse.tooling.oracle.OraclePackageDescribeParser.parse(OraclePackageDescribeParser.java:55)
	at com.googlecode.goclipse.core.engine.GoEngineClient$GoStructureUpdateTask.createSourceFileStructure(GoEngineClient.java:109)
	at melnorme.lang.ide.core.engine.StructureModelManager$StructureUpdateTask.doRun(StructureModelManager.java:325)
	at melnorme.lang.ide.core.engine.StructureModelManager$StructureUpdateTask.run(StructureModelManager.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The file is here: http://pastebin.com/Ve8TiEu3

How do I retrieve oracle or gocode logs?

**Comment by bruno-medeiros** [comment]
@RomanSaveljev Thx. I was able to replicate your error with that source code (and then I simplified it). I've created a new issue for it: https://github.com/GoClipse/goclipse/issues/156

**Comment by honzajde** [comment]
I updated by calling `go get golang.org/x/tools/cmd/oracle` to the latest version. (Btw. I don't know how to make oracle print it's version!? -v, -version --version don't do anything). And this solved the problem - outline now shows.
Thanks @bruno-medeiros

**Comment by bruno-medeiros** [comment]
Yeah, the versioning scheme for oracle isn't clear. I think it's updated with each Go toolchain release though.
